### ISSUE TITLE
in 1.3.1. still broken kokr korean font

### ISSUE THREAD

**Issue by 5t5i1v3r** [Larsj02/Remix-Gem-Helper#11]
![2024-05-19 22 53 57](https://github.com/Larsj02/Remix-Gem-Helper/assets/133852038/76e01f81-8494-422d-a270-f9ddfab1bda6)

3x FontString:SetText(): Font not set
Lua Taint: Remix Gem Helper
[string "=[C]"]: in function `SetText'
[string "@Remix Gem Helper/Core.lua"]:97: in function `initializer'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:396: in function `InvokeInitializer'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:405: in function `InvokeInitializers'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:718: in function `Update'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:192: in function `FullUpdateInternal'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:692: in function `FullUpdateInternal'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:146: in function `FullUpdate'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:663: in function <...ddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua:662>
[string "=[C]"]: ?
[string "@Blizzard_SharedXML/CallbackRegistry.lua"]:178: in function <...rfaceBlizzard_SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
...
[string "@Remix Gem Helper/Core.lua"]:334: in function <Remix Gem Helper/Core.lua:333>
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:458: in function `SetUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:301: in function `ShowUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:165: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:161>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:769: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:748>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Blizzard_UIPanels_Game/Mainline/CharacterFrame.lua"]:25: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

Locals:
(*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = "Meta (|cff2ecc711/1|r)"

Thanks for making such a great addon.
I hope this issue is resolved.

**Comment by Larsj02** [comment]
Fixed in the newest commit you can either download the fix from github or wait till i release it. Another option would be just renaming the files by hand.
go to addons then Remix Gem Helper\Media\Fonts\koKR
and rename NotoSansKR-Bold.ttf to NotoSans-Bold.ttf you could do that with the other fonts too but I'm currently just using the Bold one
