### ISSUE TITLE
lua bug

### ISSUE THREAD

**Issue by I-AM-T3X** [Larsj02/Remix-Gem-Helper#13]
2x Remix Gem Helper/GemUtil.lua:222: attempt to index local 'cacheInfo' (a nil value)
[string "@Remix Gem Helper/GemUtil.lua"]:222: in function `GetFilteredGems'
[string "@Remix Gem Helper/Core.lua"]:289: in function `selectionTreeUpdate'
[string "@Remix Gem Helper/Core.lua"]:302: in function <Remix Gem Helper/Core.lua:130>
[string "@Remix Gem Helper/Core.lua"]:378: in function <Remix Gem Helper/Core.lua:358>

Locals:
self = <table> {
 GetSocketTypeName = <function> defined @Remix Gem Helper/GemUtil.lua:29
 AddGemData = <function> defined @Remix Gem Helper/GemUtil.lua:86
 GetGemSocketType = <function> defined @Remix Gem Helper/GemUtil.lua:151
 owned_gems = <table> {
 }
 GetSocketTypeInfo = <function> defined @Remix Gem Helper/GemUtil.lua:18
 RefreshOwnedGems = <function> defined @Remix Gem Helper/GemUtil.lua:120
 GetSocketsInfo = <function> defined @Remix Gem Helper/GemUtil.lua:39
 GetGemStats = <function> defined @Remix Gem Helper/GemUtil.lua:239
 GetFilteredGems = <function> defined @Remix Gem Helper/GemUtil.lua:186
 GetItemGems = <function> defined @Remix Gem Helper/GemUtil.lua:155
}
socketTypeFilter = "ALL"
nameFilter = ""
validGems = <table> {
 META = <table> {
 }
 COGWHEEL = <table> {
 }
 PRIMORDIAL = <table> {
 }
 PRISMATIC = <table> {
 }
 TINKER = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 217907 = "TINKER"
 218082 = "COGWHEEL"
 204001 = "PRIMORDIAL"
 218003 = "COGWHEEL"
 219817 = "TINKER"
 212749 = "TINKER"
 204002 = "PRIMORDIAL"
 204018 = "PRIMORDIAL"
 218004 = "COGWHEEL"
 204029 = "PRIMORDIAL"
 216639 = "PRISMATIC"
 220211 = "META"
 216671 = "META"
 217957 = "TINKER"
 219878 = "META"
 219386 = "META"
 218005 = "COGWHEEL"
 216624 = "TINKER"
 216640 = "PRISMATIC"
 204022 = "PRIMORDIAL"
 220374 = "PRISMATIC"
 220117 = "META"
 204004 = "PRIMORDIAL"
 204020 = "PRIMORDIAL"
 219523 = "TINKER"
 216625 = "TINKER"
 216641 = "PRISMATIC"
 217927 = "TINKER"
 217989 = "COGWHEEL"
 220372 = "PRISMATIC"
 204005 = "PRIMORDIAL"
 204021 = "PRIMORDIAL"
 204011 = "PRIMORDIAL"
 219801 = "TINKER"
 219944 = "TINKER"
 219452 = "TINKER"
 204013 = "PRIMORDIAL"
 211102 = "PRISMATIC"
 204006 = "PRIMORDIAL"
 219389 = "TINKER"
 220367 = "PRISMATIC"
 216627 = "TINKER"
 221977 = "META"
 204012 = "PRIMORDIAL"
 204003 = "PRIMORDIAL"
 220120 = "META"
 204007 = "PRIMORDIAL"
 216642 = "PRISMATIC"
 219527 = "TINKER"
 216628 = "TINKER"
 216644 = "PRISMATIC"
 211109 = "PRISMATIC"
 204019 = "PRIMORDIAL"
 211101 = "PRISMATIC"
 211124 = "PRISMATIC"
 210716 = "PRISMATIC"
 211103 = "PRISMATIC"
 216629 = "COGWHEEL"
 210718 = "PRISMATIC"
 210717 = "PRISMATIC"
 211125 = "PRISMATIC"
 211105 = "PRISMATIC"
 204009 = "PRIMORDIAL"
 204025 = "PRIMORDIAL"
 220369 = "PRISMATIC"
 216630 = "COGWHEEL"
 218043 = "COGWHEEL"
 220370 = "PRISMATIC"
 220368 = "PRISMATIC"
 217964 = "TINKER"
 204010 = "PRIMORDIAL"
 212916 = "TINKER"
 220373 = "PRISMATIC"
 216631 = "COGWHEEL"
 218044 = "COGWHEEL"
 216663 = "META"
 212361 = "TINKER"
 216695 = "META"
 216711 = "META"
 204027 = "PRIMORDIAL"
 220371 = "PRISMATIC"
 216632 = "COGWHEEL"
 221982 = "META"
 219516 = "TINKER"
 212362 = "TINKER"
 212759 = "TINKER"
 218109 = "COGWHEEL"
 211107 = "PRISMATIC"
 216643 = "PRISMATIC"
 217903 = "TINKER"
 218046 = "COGWHEEL"
 210681 = "PRISMATIC"
 211123 = "PRISMATIC"
 212760 = "TINKER"
 218110 = "COGWHEEL"
 219777 = "TINKER"
 210714 = "PRISMATIC"
 211108 = "PRISMATIC"
 216650 = "TINKER"
 211106 = "PRISMATIC"
 210715 = "PRISMATIC"
 211110 = "PRISMATIC"
 204014 = "PRIMORDIAL"
 204030 = "PRIMORDIAL"
 216626 = "TINKER"
 217961 = "TINKER"
 216651 = "TINKER"
 212758 = "TINKER"
 212365 = "TINKER"
 216647 = "TINKER"
 204015 = "PRIMORDIAL"
 212694 = "TINKER"
 216648 = "TINKER"
 216649 = "TINKER"
 219818 = "TINKER"
 217983 = "COGWHEEL"
 212366 = "TINKER"
 204000 = "PRIMORDIAL"
 218045 = "COGWHEEL"
 218108 = "COGWHEEL"
}
(for control) = 216639
gemItemID = 216639
gemType = "PRISMATIC"
dupeID = false
cacheInfo = nil
(*temporary) = <table> {
 CacheItemInfo = <function> defined @Remix Gem Helper/Cache.lua:33
 itemInfo = <table> {
 }
 GetItemInfo = <function> defined @Remix Gem Helper/Cache.lua:55
}
(*temporary) = 216639
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined @Remix Gem Helper/Cache.lua:33
(*temporary) = <table> {
 CacheItemInfo = <function> defined @I

**Comment by Larsj02** [comment]
should be fixed now
