### ISSUE TITLE
Cloak tooltip

### ISSUE THREAD

**Issue by Dairyman** [Larsj02/Remix-Gem-Helper#15]
You can 
https://github.com/Larsj02/Remix-Gem-Helper/blob/d7038cfddc0f2c69183af51bcb124768143f8770/CloakTooltip.lua#L22-L31
change with
```Lua
local function updateItemTooltip(tooltip, tooltipData)
    if tooltipData.id ~= const.CLOAK_BUFF.ITEM_ID or not tooltipData.guid then return end
    local guid = tooltipData.guid
    if not guid or not C_Item.IsItemGUIDInInventory(guid) then return end

    tooltip.TextLeft1:SetText((tooltip.TextLeft1:GetText() or "") .. getCloakLevel())
    local stats = getCloakStats()
    if stats then
        tooltip.TextLeft2:SetText((tooltip.TextLeft2:GetText() or "").. "\n" .. stats)
    end
end

```
Simpler check if it is the cloak and check if it yours so it does not display your stats on other players cloaks. Plus a check for stats as this can be nil when you do not wear the cloak.

**Comment by Larsj02** [comment]
Thanks add this

**Comment by Larsj02** [comment]
In the future if you wanna update stuff you can also just make a pull request and i'll take a look :)
