### ISSUE TITLE
FYI: C_TooltipInfo

### ISSUE THREAD

**Issue by Dairyman** [Larsj02/Remix-Gem-Helper#5]
FYI: There is [C_TooltipInfo.GetHyperlink](https://warcraft.wiki.gg/wiki/API_C_TooltipInfo.GetHyperlink) which does the same without invoking the GameTooltip.
https://github.com/Larsj02/Remix-Gem-Helper/blob/6e76506776242b7067eb73e53425ae4c0177b345/Cache.lua#L18-L19

**Comment by Larsj02** [comment]
Thanks changed that!
