### ISSUE TITLE
Invalid gemstone names in cyrillic

### ISSUE THREAD

**Issue by tna0y** [Larsj02/Remix-Gem-Helper#6]
Font used for gem names seems not to support non-latin alphabets. An example for cyrillic is provided.

<img width="696" alt="image" src="https://github.com/Larsj02/Remix-Gem-Helper/assets/22504374/5525c233-dd42-4b1a-b75b-a536ae6c807e">

**Comment by Larsj02** [comment]
Fixed in 1.3.0
