### ISSUE TITLE
Still Text broken in non-English client

### ISSUE THREAD

**Issue by vonvoyage1** [Larsj02/Remix-Gem-Helper#7]
![Broken](https://github.com/Larsj02/Remix-Gem-Helper/assets/142294086/489d042b-5fe9-4e53-93f7-d82d45179b07)

And 

In ver 1.2.1, font replacement ( with same font name ) did work.
So I used my own Kokr font instead.

But recent version, font replacement Doesn't work neither.

I hope it can be fixed.

Thank you for your work.

**Comment by Larsj02** [comment]
Which language ?

**Comment by Larsj02** [comment]
Fixed in next release
